// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDbG2Lv2FdXjr2yZ7-FlZ3WGc0zhOuXN4',
    appId: '1:640325875666:web:284e39e12eee821bf8fa0b',
    messagingSenderId: '640325875666',
    projectId: 'flutterproeyectofinal',
    authDomain: 'flutterproeyectofinal.firebaseapp.com',
    storageBucket: 'flutterproeyectofinal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7IIE35Jl7f4odFU3STW_LBOa_w1vkc4M',
    appId: '1:640325875666:android:a6f2d816a8024336f8fa0b',
    messagingSenderId: '640325875666',
    projectId: 'flutterproeyectofinal',
    storageBucket: 'flutterproeyectofinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpArXd_t-4PdLO3pdT7pj7aPgHlQte4Y',
    appId: '1:640325875666:ios:4836a41ac6e9a750f8fa0b',
    messagingSenderId: '640325875666',
    projectId: 'flutterproeyectofinal',
    storageBucket: 'flutterproeyectofinal.appspot.com',
    iosBundleId: 'com.example.gifmundo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYpArXd_t-4PdLO3pdT7pj7aPgHlQte4Y',
    appId: '1:640325875666:ios:4836a41ac6e9a750f8fa0b',
    messagingSenderId: '640325875666',
    projectId: 'flutterproeyectofinal',
    storageBucket: 'flutterproeyectofinal.appspot.com',
    iosBundleId: 'com.example.gifmundo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDbG2Lv2FdXjr2yZ7-FlZ3WGc0zhOuXN4',
    appId: '1:640325875666:web:a9071c7ec7d3c34af8fa0b',
    messagingSenderId: '640325875666',
    projectId: 'flutterproeyectofinal',
    authDomain: 'flutterproeyectofinal.firebaseapp.com',
    storageBucket: 'flutterproeyectofinal.appspot.com',
  );
}
